#!/usr/bin/env python

import re
import sys

from subprocess import *

p = Popen(
    "pylint -f parseable -r n %s"%
    sys.argv[1], shell = True, stdout = PIPE).stdout

for line in p:
    match = re.search("\\[([WECRF])(, (.+?))?\\]", line)
    if match:
        kind = match.group(1)
        func = match.group(3)

        if kind in ["W","C","R","F"]:
           msg = "Warning"
        else:
           msg = "Error"

        if func:
            line = re.sub("\\[([WECRF])(, (.+?))?\\]",
                          "%s (%s):" % (msg, func), line)
        else:
            line = re.sub("\\[([WECRF])?\\]", "%s:" % msg, line)
    print line,

p.close()